graph TD
    n-workers-agent-host-a5cfa4["agent-host\nworkers/agent-host"]
    n-workers-document-worker-448c93["document-worker\nworkers/document-worker"]
    n-workers-domain-worker-32db39["domain-worker\nworkers/domain-worker"]
    n-workers-media-worker-aa3374["media-worker\nworkers/media-worker"]
    n-workers-research-worker-1ef7c3["research-worker\nworkers/research-worker"]
    n-workers-task-worker-fd7b7b["task-worker\nworkers/task-worker"]
