// @generated by scripts/gen-design-tokens.mjs — do not edit.
// 正は shared/design/tokens.json。値を変えたら `pnpm gen:design-tokens`。
import AppKit

enum PointerMetrics {
    static let pointerHeight: CGFloat = 22
    static let pointerWidth: CGFloat = 22
    static let outerStroke: CGFloat = 3
    static let innerStroke: CGFloat = 2
    static let glowRadius: CGFloat = 26
    static let glowAlpha: CGFloat = 0.3
    static let badgePaddingH: CGFloat = 12
    static let badgePaddingV: CGFloat = 8
    static let badgeGap: CGFloat = 8
    static let badgeMaxWidth: CGFloat = 280
    static let badgeMinWidth: CGFloat = 120
    static let badgeRadius: CGFloat = 8
    static let screenMargin: CGFloat = 8
    static let focusPadding: CGFloat = 6
    static let focusStroke: CGFloat = 3
    static let focusFillAlpha: CGFloat = 0.1
    static let stopWidth: CGFloat = 88
    static let stopHeight: CGFloat = 32
    static let titleSize: CGFloat = 14
    static let statusSize: CGFloat = 13
    static let moveSeconds: Double = 0.180
    static let holdNanoseconds: UInt64 = 900000000
    static var accent: NSColor { NSColor(srgbRed: 0.1098, green: 0.4353, blue: 0.6275, alpha: 1) }
    static var surface: NSColor { NSColor(srgbRed: 0.0902, green: 0.1020, blue: 0.1255, alpha: 1) }
    static var text: NSColor { NSColor(srgbRed: 0.9490, green: 0.9569, blue: 0.9686, alpha: 1) }
    static var outline: NSColor { NSColor(srgbRed: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1) }
    static var darkOutline: NSColor { NSColor(srgbRed: 0.0902, green: 0.0980, blue: 0.1137, alpha: 1) }
}
