// @generated by scripts/gen-design-tokens.mjs — do not edit.
// 正は shared/design/tokens.json。値を変えたら `pnpm gen:design-tokens`。
import CoreGraphics
import SwiftUI

/// 手書き案の寸法（logical points）。両 OS 共通の数値を Swift へ生成したもの。
enum Metrics {
    static let homeComposerEditorHeight: CGFloat = 84
    static let homeContentWidth: CGFloat = 760
    static let workspaceWidth: CGFloat = 1080
    static let workspaceHeight: CGFloat = 680
    static let workspaceRadius: CGFloat = 28
    static let notchWidth: CGFloat = 304
    static let notchDepth: CGFloat = 25
    static let notchShoulder: CGFloat = 30
    static let dockWidth: CGFloat = 296
    static let dockHeight: CGFloat = 42
    static let hudWidth: CGFloat = 220
    static let hudHeight: CGFloat = 44
    static let hudBottomRadius: CGFloat = 18
    static let hudTopRadius: CGFloat = 10
    static let dockIdleWidth: CGFloat = 220
    static let dockIdleHeight: CGFloat = 44
    static let dockContextWidth: CGFloat = 320
    static let dockContextHeight: CGFloat = 52
    static let dockContextExpandedWidth: CGFloat = 700
    static let dockContextExpandedBase: CGFloat = 180
    static let dockListeningWidth: CGFloat = 600
    static let dockListeningHeight: CGFloat = 120
    static let dockThinkingWidth: CGFloat = 560
    static let dockThinkingHeight: CGFloat = 88
    static let dockAgentWidth: CGFloat = 720
    static let dockAgentHeightBase: CGFloat = 190
    static let dockAgentRowHeight: CGFloat = 36
    static let dockResultWidth: CGFloat = 520
    static let dockResultHeight: CGFloat = 150
    static let dockConfirmWidth: CGFloat = 560
    static let dockConfirmHeight: CGFloat = 176
    static let dockConfirmPrimaryMinWidth: CGFloat = 96
    static let dockMeetingWidth: CGFloat = 820
    static let dockMeetingHeight: CGFloat = 76
    static let dockMeetingExpandedHeight: CGFloat = 460
    static let dockTitleSize: CGFloat = 20
    static let dockSpeechSize: CGFloat = 18
    static let dockPrimarySize: CGFloat = 16
    static let dockRowSize: CGFloat = 15
    static let dockMetaSize: CGFloat = 13
    static let dockLabelSize: CGFloat = 11
    static let dockPadH: CGFloat = 20
    static let dockPadV: CGFloat = 16
    static let dockRowGap: CGFloat = 8
    static let hudOrbSize: CGFloat = 36
    static let hudOrbCompactSize: CGFloat = 22
    static let paletteWidth: CGFloat = 140
    static let assistantWidth: CGFloat = 180
    static let paletteRadius: CGFloat = 12
    static let intentReadyWidth: CGFloat = 560
    static let intentReadyHeight: CGFloat = 56
    static let intentTypingWidth: CGFloat = 640
    static let intentTypingHeightMax: CGFloat = 140
    static let intentListeningWidth: CGFloat = 560
    static let intentListeningHeight: CGFloat = 96
    static let intentContextPeekWidth: CGFloat = 640
    static let intentContextPeekHeightMax: CGFloat = 220
    static let intentBottomInset: CGFloat = 60
    static let intentRadius: CGFloat = 16
    static let recordingIndicatorWidth: CGFloat = 390
    static let recordingIndicatorHeight: CGFloat = 52
    static let recordingIndicatorRadius: CGFloat = 12
    static let sidebarWidth: CGFloat = 260
    static let sidebarCollapsed: CGFloat = 64
    static let topBarHeight: CGFloat = 56
    static let mainMinWidth: CGFloat = 640
    static let inspectorWidth: CGFloat = 360
    static let composerMinHeight: CGFloat = 48
    static let composerMaxHeight: CGFloat = 72
    static let bpThreeColumn: CGFloat = 1280
    static let bpInspectorDrawer: CGFloat = 960
    static let bpSidebarCollapse: CGFloat = 720
    static let wsGutter: CGFloat = 22
    static let wsContentTop: CGFloat = 62
    static let wsColumnGap: CGFloat = 18
    static let wsRightColumn: CGFloat = 320
    static let wsRagDrawer: CGFloat = 200
    static let wsBottomBar: CGFloat = 52
    static let wsStatusBar: CGFloat = 48
    static let wsAskBar: CGFloat = 52
    static let hoverDelta: CGFloat = 0.06
    static let pressedDelta: CGFloat = 0.11
    static let pressedScale: CGFloat = 0.97
    static let focusRing: CGFloat = 2
}

/// 遷移の時間（秒）。
enum Motion {
    static let showMs: Double = 0.120
    static let hideMs: Double = 0.100
    static let drawerMs: Double = 0.180
    static let hoverMs: Double = 0.110
    static let dockResizeMs: Double = 0.180
    static let dockContentDelayMs: Double = 0.055
}

/// §17.1 カラートークン（Light/Dark）。UI に直書きせずここから使う。
enum Palette {
    static func canvas(_ dark: Bool) -> Color { dark ? canvasDark : canvasLight }
    static func surface(_ dark: Bool) -> Color { dark ? surfaceDark : surfaceLight }
    static func text(_ dark: Bool) -> Color { dark ? textDark : textLight }
    static func muted(_ dark: Bool) -> Color { dark ? mutedDark : mutedLight }
    static func border(_ dark: Bool) -> Color { dark ? borderDark : borderLight }
    static func accent(_ dark: Bool) -> Color { dark ? accentDark : accentLight }
    static func success(_ dark: Bool) -> Color { dark ? successDark : successLight }
    static func warning(_ dark: Bool) -> Color { dark ? warningDark : warningLight }
    static func danger(_ dark: Bool) -> Color { dark ? dangerDark : dangerLight }
    static let canvasLight = Color(.sRGB, red: 0.9647, green: 0.9608, blue: 0.9412)
    static let canvasDark = Color(.sRGB, red: 0.0902, green: 0.1020, blue: 0.0902)
    static let surfaceLight = Color(.sRGB, red: 1.0000, green: 0.9961, blue: 0.9804)
    static let surfaceDark = Color(.sRGB, red: 0.1255, green: 0.1412, blue: 0.1255)
    static let textLight = Color(.sRGB, red: 0.1255, green: 0.1451, blue: 0.1216)
    static let textDark = Color(.sRGB, red: 0.9490, green: 0.9412, blue: 0.9176)
    static let mutedLight = Color(.sRGB, red: 0.3843, green: 0.4039, blue: 0.3725)
    static let mutedDark = Color(.sRGB, red: 0.6549, green: 0.6784, blue: 0.6510)
    static let borderLight = Color(.sRGB, red: 0.8471, green: 0.8549, blue: 0.8235)
    static let borderDark = Color(.sRGB, red: 0.1882, green: 0.2078, blue: 0.1882)
    static let accentLight = Color(.sRGB, red: 0.6588, green: 0.2314, blue: 0.1843)
    static let accentDark = Color(.sRGB, red: 0.8431, green: 0.4549, blue: 0.4039)
    static let successLight = Color(.sRGB, red: 0.0941, green: 0.4745, blue: 0.3059)
    static let successDark = Color(.sRGB, red: 0.2353, green: 0.7961, blue: 0.4980)
    static let warningLight = Color(.sRGB, red: 0.7098, green: 0.2784, blue: 0.0314)
    static let warningDark = Color(.sRGB, red: 0.9569, green: 0.7216, blue: 0.3765)
    static let dangerLight = Color(.sRGB, red: 0.7059, green: 0.1373, blue: 0.0941)
    static let dangerDark = Color(.sRGB, red: 1.0000, green: 0.4549, blue: 0.4235)
}

/// §17.2 タイポグラフィ（pt / weight）。
enum TypeScale {
    static let workspaceTitleSize: CGFloat = 32
    static let workspaceTitleWeight: Font.Weight = .semibold
    static let pageTitleSize: CGFloat = 28
    static let pageTitleWeight: Font.Weight = .semibold
    static let sectionTitleSize: CGFloat = 22
    static let sectionTitleWeight: Font.Weight = .semibold
    static let cardTitleSize: CGFloat = 18
    static let cardTitleWeight: Font.Weight = .semibold
    static let primarySize: CGFloat = 17
    static let primaryWeight: Font.Weight = .medium
    static let bodySize: CGFloat = 16
    static let bodyWeight: Font.Weight = .regular
    static let secondarySize: CGFloat = 14
    static let secondaryWeight: Font.Weight = .regular
    static let microSize: CGFloat = 12
    static let microWeight: Font.Weight = .medium
    static let captionSize: CGFloat = 11
    static let captionWeight: Font.Weight = .regular
}

/// §17.3 余白・角丸（pt）。
enum Space {
    static let base: CGFloat = 8
    static let compact: CGFloat = 4
    static let cardPadding: CGFloat = 18
    static let largePadding: CGFloat = 24
    static let radiusSmall: CGFloat = 8
    static let radiusStandard: CGFloat = 12
    static let radiusTaskDock: CGFloat = 16
}
