graph TD
    n-apps-802508["apps\napps"]
    n-artifacts-3dc528["artifacts\nartifacts"]
    n-core-94a042["core\ncore"]
    n-docs-71ab8b["docs\ndocs"]
    n-evals-64bacb["evals\nevals"]
    n-infra-5e03a5["infra\ninfra"]
    n-package-json-7030d0["package.json\npackage.json"]
    n-packages-d8ae08["packages\npackages"]
