// <auto-generated by scripts/gen-design-tokens.mjs — do not edit.>
// 正は shared/design/tokens.json。値を変えたら `pnpm gen:design-tokens`。
namespace Genie;

/// <summary>手書き案の寸法（effective px）。両 OS 共通の数値を Windows へ生成したもの。</summary>
public static class Metrics
{
    public const double HomeComposerEditorHeight = 84;
    public const double HomeContentWidth = 760;
    public const double WorkspaceWidth = 1080;
    public const double WorkspaceHeight = 680;
    public const double WorkspaceRadius = 28;
    public const double NotchWidth = 304;
    public const double NotchDepth = 25;
    public const double NotchShoulder = 30;
    public const double DockWidth = 296;
    public const double DockHeight = 42;
    public const double HudWidth = 220;
    public const double HudHeight = 44;
    public const double HudBottomRadius = 18;
    public const double HudTopRadius = 10;
    public const double DockIdleWidth = 220;
    public const double DockIdleHeight = 44;
    public const double DockContextWidth = 320;
    public const double DockContextHeight = 52;
    public const double DockContextExpandedWidth = 700;
    public const double DockContextExpandedBase = 180;
    public const double DockListeningWidth = 600;
    public const double DockListeningHeight = 120;
    public const double DockThinkingWidth = 560;
    public const double DockThinkingHeight = 88;
    public const double DockAgentWidth = 720;
    public const double DockAgentHeightBase = 190;
    public const double DockAgentRowHeight = 36;
    public const double DockResultWidth = 520;
    public const double DockResultHeight = 150;
    public const double DockConfirmWidth = 560;
    public const double DockConfirmHeight = 176;
    public const double DockConfirmPrimaryMinWidth = 96;
    public const double DockMeetingWidth = 820;
    public const double DockMeetingHeight = 76;
    public const double DockMeetingExpandedHeight = 460;
    public const double DockTitleSize = 20;
    public const double DockSpeechSize = 18;
    public const double DockPrimarySize = 16;
    public const double DockRowSize = 15;
    public const double DockMetaSize = 13;
    public const double DockLabelSize = 11;
    public const double DockPadH = 20;
    public const double DockPadV = 16;
    public const double DockRowGap = 8;
    public const double HudOrbSize = 36;
    public const double HudOrbCompactSize = 22;
    public const double PaletteWidth = 140;
    public const double AssistantWidth = 180;
    public const double PaletteRadius = 12;
    public const double IntentReadyWidth = 560;
    public const double IntentReadyHeight = 56;
    public const double IntentTypingWidth = 640;
    public const double IntentTypingHeightMax = 140;
    public const double IntentListeningWidth = 560;
    public const double IntentListeningHeight = 96;
    public const double IntentContextPeekWidth = 640;
    public const double IntentContextPeekHeightMax = 220;
    public const double IntentBottomInset = 60;
    public const double IntentRadius = 16;
    public const double RecordingIndicatorWidth = 390;
    public const double RecordingIndicatorHeight = 52;
    public const double RecordingIndicatorRadius = 12;
    public const double SidebarWidth = 260;
    public const double SidebarCollapsed = 64;
    public const double TopBarHeight = 56;
    public const double MainMinWidth = 640;
    public const double InspectorWidth = 360;
    public const double ComposerMinHeight = 48;
    public const double ComposerMaxHeight = 72;
    public const double BpThreeColumn = 1280;
    public const double BpInspectorDrawer = 960;
    public const double BpSidebarCollapse = 720;
    public const double WsGutter = 22;
    public const double WsContentTop = 62;
    public const double WsColumnGap = 18;
    public const double WsRightColumn = 320;
    public const double WsRagDrawer = 200;
    public const double WsBottomBar = 52;
    public const double WsStatusBar = 48;
    public const double WsAskBar = 52;
    public const double HoverDelta = 0.06;
    public const double PressedDelta = 0.11;
    public const double PressedScale = 0.97;
    public const double FocusRing = 2;
}

/// <summary>遷移の時間（ミリ秒）。</summary>
public static class Motion
{
    public const int ShowMs = 120;
    public const int HideMs = 100;
    public const int DrawerMs = 180;
    public const int HoverMs = 110;
    public const int DockResizeMs = 180;
    public const int DockContentDelayMs = 55;
}

/// <summary>§17.1 カラートークン（Light/Dark, #AARRGGBB は不要な #RRGGBB 文字列）。</summary>
public static class Palette
{
    public const string CanvasLight = "#F6F5F0";
    public const string CanvasDark = "#171A17";
    public const string SurfaceLight = "#FFFEFA";
    public const string SurfaceDark = "#202420";
    public const string TextLight = "#20251F";
    public const string TextDark = "#F2F0EA";
    public const string MutedLight = "#62675F";
    public const string MutedDark = "#A7ADA6";
    public const string BorderLight = "#D8DAD2";
    public const string BorderDark = "#303530";
    public const string AccentLight = "#A83B2F";
    public const string AccentDark = "#D77467";
    public const string SuccessLight = "#18794E";
    public const string SuccessDark = "#3CCB7F";
    public const string WarningLight = "#B54708";
    public const string WarningDark = "#F4B860";
    public const string DangerLight = "#B42318";
    public const string DangerDark = "#FF746C";
}

/// <summary>§17.2 タイポグラフィ（pt / weight）。</summary>
public static class TypeScale
{
    public const double WorkspaceTitleSize = 32;
    public const int WorkspaceTitleWeight = 700;
    public const double PageTitleSize = 28;
    public const int PageTitleWeight = 600;
    public const double SectionTitleSize = 22;
    public const int SectionTitleWeight = 600;
    public const double CardTitleSize = 18;
    public const int CardTitleWeight = 600;
    public const double PrimarySize = 17;
    public const int PrimaryWeight = 500;
    public const double BodySize = 16;
    public const int BodyWeight = 400;
    public const double SecondarySize = 14;
    public const int SecondaryWeight = 400;
    public const double MicroSize = 12;
    public const int MicroWeight = 500;
    public const double CaptionSize = 11;
    public const int CaptionWeight = 400;
}

/// <summary>§17.3 余白・角丸（pt）。</summary>
public static class Space
{
    public const double Base = 8;
    public const double Compact = 4;
    public const double CardPadding = 18;
    public const double LargePadding = 24;
    public const double RadiusSmall = 8;
    public const double RadiusStandard = 12;
    public const double RadiusTaskDock = 16;
}
