graph TD
    n-apps-browser-extension-81dab3["browser-extension\napps/browser-extension"]
    n-apps-desktop-27ce27["desktop\napps/desktop"]
    n-apps-genie-macos-5e0241["genie-macos\napps/genie-macos"]
    n-apps-share-web-a3a108["share-web\napps/share-web"]
    n-apps-windows-afc0d1["windows\napps/windows"]
