graph TD
    n-plugins-440c33["plugins\nplugins"]
    n-scripts-16728d["scripts\nscripts"]
    n-services-3e7aaa["services\nservices"]
    n-shared-d18aac["shared\nshared"]
    n-tools-0284c6["tools\ntools"]
    n-workers-f74e09["workers\nworkers"]
