graph TD
    n-packages-policy-413b78["policy\npackages/policy"]
    n-packages-stt-cb6a2a["stt\npackages/stt"]
    n-packages-telemetry-88cac3["telemetry\npackages/telemetry"]
    n-packages-tts-05c7b7["tts\npackages/tts"]
    n-packages-ui-kit-761106["ui-kit\npackages/ui-kit"]
