/** Offline regression histories generated by the actual previous-revision workflow.
 * To regenerate explicitly: ASTRA_CAPTURE_REPLAY=1 ASTRA_TEST_TEMPORAL_PATH=/cached/temporal pnpm --filter @genie/service-task test test/replay-history.test.ts
 * Fixture activities have no database/provider effects; this is not production history.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TestWorkflowEnvironment } from '@temporalio/testing';
import { Worker } from '@temporalio/worker';
import { createRequire } from 'node:module';
// Use the exact protobuf version bundled with Temporal, without a second dependency version.
const require = createRequire(import.meta.url);
const temporalRequire = createRequire(require.resolve('@temporalio/worker'));
const History = temporalRequire('@temporalio/proto').temporal.api.history.v1.History;
import { describe, expect, it } from 'vitest';

const revision = '28f89f2636a3b780e813ea902e07d2e4900a6e3f';
const fixtureDir = fileURLToPath(new URL('./replay-fixtures/', import.meta.url));
const workflowsPath = fileURLToPath(new URL('../src/workflows.ts', import.meta.url));
const sha256 = (data: string) => createHash('sha256').update(data).digest('hex');

it.skipIf(process.env['ASTRA_CAPTURE_REPLAY'] !== '1')(
  'capture previous-revision histories on an isolated real Temporal server',
  async () => {
    const executable = process.env['ASTRA_TEST_TEMPORAL_PATH'];
    if (!executable)
      throw new Error(
        'An explicit cached Temporal executable is required; never download implicitly.',
      );
    const dir = await realpath(await mkdtemp(path.join(tmpdir(), 'genie-replay-old-')));
    const sources: Record<string, string> = {};
    let env: TestWorkflowEnvironment | undefined;
    let worker: Worker | undefined;
    let running: Promise<void> | undefined;
    let release: (() => void) | undefined;
    try {
      for (const name of ['workflows.ts', 'plan.ts']) {
        const source = execFileSync('git', ['show', `${revision}:services/task/src/${name}`], {
          encoding: 'utf8',
        });
        sources[name] = sha256(source);
        await writeFile(path.join(dir, name), source);
      }
      await symlink(
        fileURLToPath(new URL('../node_modules', import.meta.url)),
        path.join(dir, 'node_modules'),
      );
      env = await TestWorkflowEnvironment.createLocal({
        client: { identity: 'genie-replay-fixture' },
        server: {
          executable: { type: 'existing-path', path: executable },
          ip: '127.0.0.1',
          ui: false,
        },
      });
      const queue = 'genie-previous-revision-replay';
      let entered: (() => void) | undefined;
      let barrier = Promise.resolve();
      worker = await Worker.create({
        connection: env.nativeConnection,
        identity: 'genie-replay-fixture',
        namespace: env.client.options.namespace,
        taskQueue: queue,
        workflowsPath: path.join(dir, 'workflows.ts'),
        activities: {
          async startTask() {},
          async requestApprovalIfNeeded() {
            return null;
          },
          async executeStep() {
            entered?.();
            await barrier;
            return { message: 'synthetic local checklist' };
          },
          async composeArtifact() {
            return 'fixture-artifact';
          },
          // Deliberately retain the old activity result contract: void, not TaskResult.
          async completeTask() {},
          async cancelTask() {},
        },
      });
      running = worker.run();
      const histories: Record<string, string> = {};
      for (const scenario of ['completed', 'cancelled']) {
        const reachedStep = new Promise<void>((resolve) => {
          entered = resolve;
        });
        barrier = new Promise<void>((resolve) => {
          release = resolve;
        });
        const handle = await env.client.workflow.start('TaskWorkflow', {
          taskQueue: queue,
          workflowId: `historical-${scenario}`,
          args: [
            {
              taskId: `fixture-${scenario}`,
              tenantId: 'synthetic-tenant',
              userId: 'synthetic-user',
              kind: 'echo',
              input: { message: 'synthetic local checklist', steps: 1 },
            },
          ],
        });
        let stepTimeout: ReturnType<typeof setTimeout> | undefined;
        try {
          await Promise.race([
            reachedStep,
            new Promise<never>((_, reject) => {
              stepTimeout = setTimeout(
                () => reject(new Error('Historical workflow did not enter fixture step')),
                10000,
              );
            }),
          ]);
        } finally {
          clearTimeout(stepTimeout);
        }
        if (scenario === 'cancelled')
          await handle.signal('cancel', { reason: 'fixture cancellation' });
        release?.();
        expect(await handle.result()).toEqual({
          status: scenario === 'completed' ? 'COMPLETED' : 'CANCELLED',
          artifactId: scenario === 'completed' ? 'fixture-artifact' : null,
        });
        const history = await handle.fetchHistory();
        const json = JSON.stringify(history, null, 2) + '\n';
        expect(json).not.toContain('task-terminal-outcome-v1');
        histories[scenario] = sha256(json);
        await writeFile(path.join(fixtureDir, `${scenario}.json`), json);
      }
      await writeFile(
        path.join(fixtureDir, 'provenance.json'),
        JSON.stringify(
          {
            revision,
            capturedAt: new Date().toISOString(),
            sourceSha256: sources,
            historySha256: histories,
            activities:
              'Local synthetic activities; completeTask and cancelTask returned undefined. No provider, database, production history, or external network.',
            platform: process.platform,
            architecture: process.arch,
            node: process.version,
          },
          null,
          2,
        ) + '\n',
      );
    } finally {
      release?.();
      worker?.shutdown();
      await running;
      await env?.teardown();
      await rm(dir, { recursive: true, force: true });
    }
  },
  60000,
);

describe('previous-revision workflow replay with old void terminal activities', () => {
  for (const scenario of ['completed', 'cancelled']) {
    it(`replays ${scenario} history without nondeterminism`, async () => {
      const json = await readFile(path.join(fixtureDir, `${scenario}.json`), 'utf8');
      const provenance = JSON.parse(
        await readFile(path.join(fixtureDir, 'provenance.json'), 'utf8'),
      );
      expect(sha256(json)).toBe(provenance.historySha256[scenario]);
      expect(provenance.revision).toBe(revision);
      expect(json).not.toContain('task-terminal-outcome-v1');
      const history = History.fromObject(JSON.parse(json));
      const terminalName = scenario === 'completed' ? 'completeTask' : 'cancelTask';
      const scheduled = history.events.find(
        (event: any) =>
          event.activityTaskScheduledEventAttributes?.activityType?.name === terminalName,
      );
      expect(scheduled).toBeDefined();
      const completed = history.events.find(
        (event: any) =>
          event.activityTaskCompletedEventAttributes?.scheduledEventId?.toString() ===
          scheduled.eventId.toString(),
      );
      expect(
        Buffer.from(
          completed.activityTaskCompletedEventAttributes.result.payloads[0].metadata.encoding,
        ).toString(),
      ).toBe('binary/null');
      await Worker.runReplayHistory({ workflowsPath }, history);
    }, 30000);
  }
});
