/** Offline regression histories generated by the actual previous-revision workflow.
 * To regenerate explicitly: ASTRA_CAPTURE_REPLAY=1 ASTRA_TEST_TEMPORAL_PATH=/cached/temporal pnpm --filter @genie/service-task exec vitest run --config scripts/replay-capture.config.ts
 * Fixture activities have no database/provider effects; this is not production history.
 */
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Worker } from '@temporalio/worker';
import { createRequire } from 'node:module';
// Use the exact protobuf version bundled with Temporal, without a second dependency version.
const require = createRequire(import.meta.url);
const temporalRequire = createRequire(require.resolve('@temporalio/worker'));
const History = temporalRequire('@temporalio/proto').temporal.api.history.v1.History;
import { describe, expect, it } from 'vitest';

const revision = '28f89f2636a3b780e813ea902e07d2e4900a6e3f';
const fixtureDir = fileURLToPath(new URL('./replay-fixtures/', import.meta.url));
const workflowsPath = fileURLToPath(new URL('../src/workflows.ts', import.meta.url));
const sha256 = (data: string) => createHash('sha256').update(data).digest('hex');

describe('previous-revision workflow replay with old void terminal activities', () => {
  for (const scenario of ['completed', 'cancelled']) {
    it(`replays ${scenario} history without nondeterminism`, async () => {
      const json = await readFile(path.join(fixtureDir, `${scenario}.json`), 'utf8');
      const provenance = JSON.parse(
        await readFile(path.join(fixtureDir, 'provenance.json'), 'utf8'),
      );
      expect(sha256(json)).toBe(provenance.historySha256[scenario]);
      expect(provenance.revision).toBe(revision);
      expect(json).not.toContain('task-terminal-outcome-v1');
      const history = History.fromObject(JSON.parse(json));
      const terminalName = scenario === 'completed' ? 'completeTask' : 'cancelTask';
      const scheduled = history.events.find(
        (event: any) =>
          event.activityTaskScheduledEventAttributes?.activityType?.name === terminalName,
      );
      expect(scheduled).toBeDefined();
      const completed = history.events.find(
        (event: any) =>
          event.activityTaskCompletedEventAttributes?.scheduledEventId?.toString() ===
          scheduled.eventId.toString(),
      );
      expect(
        Buffer.from(
          completed.activityTaskCompletedEventAttributes.result.payloads[0].metadata.encoding,
        ).toString(),
      ).toBe('binary/null');
      await Worker.runReplayHistory({ workflowsPath }, history);
    }, 30000);
  }
});
