graph TD
    n-packages-agent-sdk-d6327d["agent-sdk\npackages/agent-sdk"]
    n-packages-api-client-bf71d3["api-client\npackages/api-client"]
    n-packages-audio-14c91c["audio\npackages/audio"]
    n-packages-contracts-de2336["contracts\npackages/contracts"]
    n-packages-db-389fab["db\npackages/db"]
    n-packages-mcp-027ee0["mcp\npackages/mcp"]
    n-packages-oauth-79c084["oauth\npackages/oauth"]
    n-packages-plugin-sdk-7c2209["plugin-sdk\npackages/plugin-sdk"]
